In [2]:
import numpy as np

## Задание 1
Задайте две матрицы 3-го порядка с помощью функции rand. Объедините их в новую матрицу двумя способами: сначала по горизонтали, а потом по вертикали.

In [6]:
arr3rd_1 = np.random.rand(3,3)
arr3rd_2 = np.random.rand(3,3)
display(arr3rd_1)
display(arr3rd_2)
display(np.hstack((arr3rd_1, arr3rd_2))) # Сложение по горизонтали
display(np.vstack((arr3rd_1, arr3rd_2))) # Сложение по вертикали

array([[0.8873721 , 0.25421657, 0.20893631],
       [0.71841194, 0.18840024, 0.85401911],
       [0.95484469, 0.42268854, 0.56116196]])

array([[0.65343899, 0.65167688, 0.72858897],
       [0.57485392, 0.06290043, 0.74535692],
       [0.50439314, 0.4711157 , 0.70120944]])

array([[0.8873721 , 0.25421657, 0.20893631, 0.65343899, 0.65167688,
        0.72858897],
       [0.71841194, 0.18840024, 0.85401911, 0.57485392, 0.06290043,
        0.74535692],
       [0.95484469, 0.42268854, 0.56116196, 0.50439314, 0.4711157 ,
        0.70120944]])

array([[0.8873721 , 0.25421657, 0.20893631],
       [0.71841194, 0.18840024, 0.85401911],
       [0.95484469, 0.42268854, 0.56116196],
       [0.65343899, 0.65167688, 0.72858897],
       [0.57485392, 0.06290043, 0.74535692],
       [0.50439314, 0.4711157 , 0.70120944]])

## Задание 2
Задайте квадратную матрицу 5-го порядка с помощью функции rand. Удалите две первые строки в этой матрице, а затем последний столбец.

In [18]:
arr_5rd = np.random.rand(5,5)
display(arr_5rd)
arr_5rd = np.delete(arr_5rd, 0, 0)
arr_5rd = np.delete(arr_5rd, 0, 0)
arr_5rd = np.delete(arr_5rd, -1, 1)
display(arr_5rd)

array([[0.33933326, 0.57558389, 0.8210084 , 0.39337189, 0.92589886],
       [0.87769983, 0.65148685, 0.40518778, 0.05448731, 0.49540131],
       [0.5230518 , 0.06158648, 0.4608074 , 0.73868422, 0.53766399],
       [0.00210432, 0.93710972, 0.36358634, 0.7674101 , 0.17969241],
       [0.00617346, 0.58157168, 0.66810346, 0.54136389, 0.99722518]])

array([[0.5230518 , 0.06158648, 0.4608074 , 0.73868422],
       [0.00210432, 0.93710972, 0.36358634, 0.7674101 ],
       [0.00617346, 0.58157168, 0.66810346, 0.54136389]])

## Задание 3
Выделите из квадратной матрицы 3-го порядка главную диагональ, побочную диагональ, (+1)-ю диагональ – на 1-н уровень выше главной, ( -1)-ю диагональ – на 1-н уровень ниже главной.

In [ ]:
arr3rd = np.random.rand(3,3)
display(arr3rd)

## Задание 4

## Задание 5

## Задание 6

## Задание 7

## Задание 8

## Задание 9

## Задание 10